________________________________________________________________________________________________________________________


* Yuvraj Sutar 
* yuvrajsutar009@gmail.com
_ _________________________________________________________________________________________________________________________
_  _________________________________________________________________________________________________________________________


# Numpy

In [1]:
import numpy as np 


In [2]:
#one dimension 
array = np.array([2,2,3,4,5,4]) 
array.shape

(6,)

In [86]:
m_list = [1,2,3]
m_list

[1, 2, 3]

In [87]:
#one or more dimensions 
m_matrix =[[4,4,3],[2,7,6],[8,0,9]]

In [88]:
m_matrix

[[4, 4, 3], [2, 7, 6], [8, 0, 9]]

In [89]:
matrix=np.array(m_matrix)
matrix

array([[4, 4, 3],
       [2, 7, 6],
       [8, 0, 9]])

In [90]:
#shape

In [91]:
matrix.shape

(3, 3)

In [92]:
np.arange(2,10,3)

array([2, 5, 8])

In [93]:
np.arange(0,11,4)

array([0, 4, 8])

In [94]:
#zeros and ones 

In [95]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [96]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [99]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [98]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [16]:
#linespace


In [17]:
np.linspace(1,1000,10) # one to 1000 in 10 values 

array([   1.,  112.,  223.,  334.,  445.,  556.,  667.,  778.,  889.,
       1000.])

In [18]:
np.linspace(0,10,3) # zero to 10 in 3 value's 

array([ 0.,  5., 10.])

In [19]:
# random values

In [108]:
a=np.random.rand(1,10,10) #uniform  

In [109]:
a

array([[[0.35441313, 0.34984478, 0.51077303, 0.20216301, 0.37888226,
         0.27653171, 0.25650182, 0.92585437, 0.45944821, 0.45795305],
        [0.74474085, 0.68904153, 0.02945527, 0.1171348 , 0.71476314,
         0.01075658, 0.18048979, 0.66296652, 0.45536611, 0.6478739 ],
        [0.13410892, 0.82815413, 0.35200563, 0.48845618, 0.42006838,
         0.36621652, 0.79526064, 0.32617352, 0.72334902, 0.54716372],
        [0.76844923, 0.80541097, 0.49292428, 0.78468823, 0.51698465,
         0.85589802, 0.94596788, 0.64373983, 0.21757073, 0.38435313],
        [0.95284302, 0.91783941, 0.36374664, 0.71048871, 0.91839546,
         0.68257163, 0.41460038, 0.67325472, 0.34170185, 0.54966049],
        [0.84850739, 0.53876958, 0.55818313, 0.98705069, 0.68013692,
         0.47084319, 0.29796844, 0.48325252, 0.38426186, 0.04921218],
        [0.70410301, 0.43700941, 0.44911268, 0.03207601, 0.23397982,
         0.98166011, 0.59546813, 0.73998366, 0.92934656, 0.09302961],
        [0.35521565, 0.3988

In [110]:
a.shape

(1, 10, 10)

In [103]:
array.shape # shape of the matrix 

(6,)

In [111]:
 b=np.random.randn(3) # n- standard deviation 


In [112]:
b

array([-0.92779107,  0.03366695,  1.06566032])

In [23]:
np.random.randn(4,4).shape 


(4, 4)

In [24]:
#randint


In [113]:
np.random.randint(1,30) #return a random integer between 1 and 30

6

In [114]:
np.random.randint(1,200,5) #generates 10 random integers between 1 and 200

array([150, 173, 104, 177, 133])

In [27]:
# array attributes 


In [28]:
import numpy as np 

In [29]:
array=np.arange(25)

In [30]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
len(array)# length of array

25

In [32]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
# reshape

In [34]:
array.reshape(5,5) # reshape of array  5 by 5 matrix's 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
#matrix aggregation

In [36]:
# specific operation or function to all elements of a matrix.
# max, min, argmax,argmin,sum

In [37]:
array=np.random.randint(0,50,25)

In [38]:
array

array([16,  3, 42, 19, 35, 29, 42,  2, 38, 36, 20, 31, 41, 11, 39, 18,  4,
       46,  0, 30, 43, 43, 36, 26, 33])

In [39]:
array.max() #maximum number in array 

46

In [40]:
array.argmax() #maximum index number /  maximum position number 

17

In [41]:
array.min() # minimum number in array 


0

In [42]:
array.argmin() #returns indices of the min element of the array/ position

18

In [43]:
array.sum() 

683

In [44]:
# shape

In [45]:
array.shape

(25,)

In [46]:
array.reshape(5,5) 

array([[16,  3, 42, 19, 35],
       [29, 42,  2, 38, 36],
       [20, 31, 41, 11, 39],
       [18,  4, 46,  0, 30],
       [43, 43, 36, 26, 33]])

In [47]:
array.reshape(1,25)

array([[16,  3, 42, 19, 35, 29, 42,  2, 38, 36, 20, 31, 41, 11, 39, 18,
         4, 46,  0, 30, 43, 43, 36, 26, 33]])

..............................................................................................................................................................................................................................................................

numpy indexing and selection

In [50]:
import numpy as np 
array=np.arange(20,30) 

In [51]:
array

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [52]:
array[-1] # negative indexing start with -1

29

In [53]:
array[0:9:3] # [start:Stop:Step]

array([20, 23, 26])

In [54]:
matrix=np.array([[1,2,3],[5,6,7]])
matrix

array([[1, 2, 3],
       [5, 6, 7]])

In [55]:
matrix[1]

array([5, 6, 7])

In [56]:
array =np.arange(20,40)

In [57]:
array

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

In [58]:
# slicing

In [59]:
array=np.arange(11)
array


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
 array[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
y=array[3:8]
y

array([3, 4, 5, 6, 7])

In [62]:
# 2 D array 

In [63]:
import numpy as np
array2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
array2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
array2d[1:,0:2] # row and col

array([[4, 5],
       [7, 8]])

In [65]:
array2d[2] # indexing 


array([7, 8, 9])

In [66]:
array2d[2,2] # Getting individual element value

9

In [67]:
array2d[2,:] # bottom row

array([7, 8, 9])

In [68]:
array2d[:,2] # last col

array([3, 6, 9])

In [69]:
# selection 



In [70]:
array=np.arange(1,22)

In [71]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21])

In [72]:
array[array <6]

array([1, 2, 3, 4, 5])

In [73]:
array[array <=6]

array([1, 2, 3, 4, 5, 6])

In [74]:
array[array >6]

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [75]:
array[array >=6]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [76]:
bool_array =array>3

In [77]:
bool_array

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [78]:
array[bool_array]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21])

In [79]:
# NumPy Operations

In [80]:
import numpy as np
arr =np.arange(0,9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [81]:
arr*2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [82]:
arr+arr

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [93]:
arr*arr

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [94]:
arr/arr

C:\Users\Yuvraj\AppData\Local\Temp/ipykernel_19632/1862401812.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([[nan,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [95]:
1/arr

C:\Users\Yuvraj\AppData\Local\Temp/ipykernel_19632/255282349.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([[       inf, 1.        , 0.5       ],
       [0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     ]])

In [96]:
arr**2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]], dtype=int32)

In [103]:
import numpy as np 
a =np.array([1,2,3,4]).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [104]:
b =np.array([11,12,13,14]).reshape(2,2)
b

array([[11, 12],
       [13, 14]])

In [105]:
a*b 

array([[11, 24],
       [39, 56]])

In [106]:
np.dot(a,b)# 1 st row multiple by 1 col and 1 st row ssecond  col

array([[37, 40],
       [85, 92]])

In [109]:
np.sqrt(arr)

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712]])

In [110]:
np.exp(arr)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03]])

In [111]:
np.max(arr)

8

In [112]:
np.min(arr)

0

In [113]:
np.tan(arr)

array([[ 0.        ,  1.55740772, -2.18503986],
       [-0.14254654,  1.15782128, -3.38051501],
       [-0.29100619,  0.87144798, -6.79971146]])

In [114]:
np.cos(arr)

array([[ 1.        ,  0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362,  0.28366219],
       [ 0.96017029,  0.75390225, -0.14550003]])

In [115]:
np.sin(arr)

array([[ 0.        ,  0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825]])

In [117]:
1/np.sign(arr)

C:\Users\Yuvraj\AppData\Local\Temp/ipykernel_19632/3313567171.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/np.sign(arr)


array([[inf,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

* Yuvraj Sutar 
* yuvrajsutar009@gmail.com